### ISSUE TITLE
State machine improvements

### ISSUE THREAD

**Issue by akiyeng2** [Team-4795/2023-Charged-Up#17]
- [x] Manual arm code doesn't work
- [x] Speed up arm control
@sjiyeng put rest of changes requested

**Comment by sjiyeng** [comment]
Intake/outtake speed controlled by state machine
Move intake vs outtake button to driver, a and b buttons
Make which d pad corresponds to what height more intuitive, will ask lee
manual control on driver controller, max speed of .1
