### ISSUE TITLE
Drivebase improvements

### ISSUE THREAD

**Issue by sjiyeng** [Team-4795/2023-Charged-Up#19]
Square the joystick input values to make robot more controllable

-can't simply square because negatives and it's weird with swerve because vector addition weird, I think

Minimum speed of .04, look at db code last year for how we did it

**Comment by paulrosu11** [comment]
Should be working under branch Swerve-squared. Yet to be tested

**Comment by sjiyeng** [comment]
minimum speed code @paulrosu11 ?

**Comment by sjiyeng** [comment]
Don't need anymore
