### ISSUE TITLE
Switch intake to CAN

### ISSUE THREAD

**Issue by sjiyeng** [Team-4795/2023-Charged-Up#20]
CAN ID 24, brushed motor, idle mode brake, 40A current limit

**Comment by natashalrp** [comment]
wdym when you say idle mode brake and 40A current limit
bc I don't remember using those in the previous version with can but I can add them if needed

also when I'm done should I just commit to main or do you want me to commit to another branch, I've been working out of main but I can move the changes to another branch

**Comment by sjiyeng** [comment]
Brake mode makes the motors resist motion when 0 output is applied. it shorts motor wires together inside the motor controller and uses the energy generated by motors that want to spin to resist spinning. 

40A current limit makes sure we don't smoke a motor

Look at arm code for implementation

work out of arm-testing
